package api

const (
	apiKey                = "apikey"
	archKey               = "arch"
	clientIDKey           = "client_id"
	deleteSubscriptionKey = "delete_subscription"
	distroKey             = "distro"
	filterTypeKey         = "filters[type]"
	filterOSKey           = "filters[os]"
	filterSortByKey       = "filters[sort_by]"
	filterSortDirKey      = "filters[sort_dir]"
	filterPageSizeKey     = "filters[page_size]"
	filterPageNumberKey   = "filters[page_number]"
	filterStateKey        = "filters[state]"
	filterNameKey         = "filters[name]"
	filterLocationKey     = "filters[location]"
	filterProductTypeKey  = "filters[product_type]"
	filterProductCodeKey  = "filters[product_code]"
	forceDeleteKey        = "force_delete"
	imageKey              = "image"
	jobIDKey              = "job_id"
	labelKey              = "label"
	locationKey           = "location"
	nameKey               = "name"
	paramKey              = "param"
	paramBackupKey        = "params[backup]"
	paramContactIDKey     = "params[contact_id]"
	paramIPv4Key          = "params[ipv4][]"
	paramIPv6Key          = "params[ipv6][]"
	paramNameKey          = "params[name]"
	paramSendEmailKey     = "params[send_email]"
	paramSSHKey           = "params[ssh_keys][]"
	planKey               = "plan"
	productKey            = "product"
	productCodeKey        = "product_code"
	stateKey              = "state"
	typeKey               = "type"
	updateLabelKey        = "updates[label]"
	updateNoteKey         = "updates[notes]"
	updateVNCKey          = "updates[vnc_screen]"
	updateKernelKey       = "update[kernel]"
	// updatePartitionThreshold = "updates[partitions][xxx][threshold]"
	upgradeCoresKey = "upgrade[cores]"
	upgradeRAMKey   = "upgrade[ram]"
	// upgradeDiskKey = "upgrade[disk][xxx]"
)
