name: Dev Release

on:
  workflow_dispatch:
  inputs:
    replaceMod:
        description: 'Replace go.mod'
        required: false

jobs:
  releaser:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6
      -
        name: Update go mod
        if: ${{ github.event.inputs.replaceMod != '' }}
        run: |
            go mod edit -replace "github.com/sitehostnz/gosh"=>"${{ github.event.inputs.replaceMod }}"
            go mod tidy

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
